### PR TITLE
fix: #85 unreliable torch

### LINKED ISSUE #85: Unreliable torch
Tested on an iPhone 11 Pro running iOS 16;

With `isTorchOn` set to `true` the torch can show three behaviours - none of which is reliable:

1. The torch will not light up
2. The torch will light up for a brief moment and then be off again.
3. The torch will not go out when the View is dismissed.

The View is presented in a Sheet:

```swift
.sheet(isPresented: $isShowingScanner) {
    CodeScannerView(
        codeTypes: [.code39],
        simulatedData: "04 ASO SCANTEST123",
        isTorchOn: true,
        completion: handleScan)
}
```

### PR DESCRIPTION
**Pull request by nitricware**
Fixes an issue where the CaptureSession became unresponsive while the torch was on or where the CaptureSession wouldn't properly start at all when the torch was on by default.
Fixes #85

### CODE REVIEW

File: Sources/CodeScanner/ScannerViewController.swift [hunk 1]
```diff
@@ -416,12 +416,14 @@ extension CodeScannerView {
...
         
         func updateViewController(isTorchOn: Bool, isGalleryPresented: Bool, isManualCapture: Bool, isManualSelect: Bool) {
-            if let backCamera = AVCaptureDevice.default(for: AVMediaType.video),
-               backCamera.hasTorch
-            {
-                try? backCamera.lockForConfiguration()
-                backCamera.torchMode = isTorchOn ? .on : .off
-                backCamera.unlockForConfiguration()
+            guard let videoCaptureDevice = parentView.videoCaptureDevice ?? fallbackVideoCaptureDevice else {
+                return
```
Comment (NathanFallet) [inline Sources/CodeScanner/ScannerViewController.swift:420]: Are you sure this works with simulator as well?
And by the way, test fails when building on iOS simulator.

**Comment by nitricware** [comment]
You're right.
Curious why it worked on my device.
With this fix it should now work.

I'm new to contributing to packages and my workflow may be sub-optimal at best (I'm sure it is)
I copied the code into my project and tweaked it until it worked. then i copied the two files back to the repository, commited and pushed and filed a pull a request. do you have any resources on how to make this better/easier?

**Comment by demolisher2000** [comment]
@NathanFallet Is it possible to merge this fix and produce a new version? We would like to use this library, but this bug is blocking us from it

**Review by NathanFallet — APPROVED** [review]
